In [1]:
import os
from PIL import Image
import numpy as np


In [2]:

rootDir = 'photos'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)

Found directory: photos
	67560840_2367169303319732_9145972439803494400_n.jpg
	67462854_2373011572735505_8116423630256078848_n.jpg
	64662785_2309017805801549_5891812488562868224_n.jpg
	67826687_2397494403620555_1532308653195919360_n.jpg
	67479175_2383192675050728_439251287523983360_n.jpg
	67404882_2383190101717652_2050868410216087552_n.jpg
	68567522_2410845008952161_5858401164873170944_n.jpg
	68696689_2415825158454146_5455201033967894528_n.jpg
	70515420_2476351362401525_4281651419913650176_n.jpg
	70703091_2474455215924473_4821236957403152384_n.jpg
	65585086_2329588593744470_4985375828473806848_n (1).jpg
	67359023_2369240373112625_2953318206783094784_n.jpg
	69360941_2423355544367774_5632310147926720512_n.jpg
	68808123_2410843708952291_4819443482139557888_n.jpg
	70617817_2463884953648166_2386711247623028736_n.jpg
	66288957_2335078166528846_3832390367508955136_n.jpg
	67365847_2373012539402075_1170948109413384192_n.jpg
	67582490_2373012446068751_2116069587182157824_n.jpg
	65959729_232755591

In [4]:
main_list = []
im = Image.open(dirName+"//"+fileList[0])

im.show()
original_array = np.array(im)
print(original_array.shape)
print(original_array.size)
print(original_array)

new_image = im.resize((200, 200))
resized_array = np.array(new_image)
print(resized_array.size)
print(resized_array.shape)
print(resized_array)
main_list.append(resized_array)

(900, 900, 3)
2430000
[[[ 83  80  75]
  [ 82  79  74]
  [ 83  80  75]
  ...
  [123 118 114]
  [121 116 112]
  [119 114 110]]

 [[ 79  76  71]
  [ 81  78  73]
  [ 84  81  76]
  ...
  [123 118 114]
  [122 117 113]
  [122 117 113]]

 [[ 79  76  71]
  [ 81  78  73]
  [ 83  80  75]
  ...
  [124 119 115]
  [127 122 118]
  [127 122 118]]

 ...

 [[ 36  35  33]
  [ 37  36  34]
  [ 38  37  35]
  ...
  [ 37  36  34]
  [ 37  36  34]
  [ 37  36  34]]

 [[ 36  35  33]
  [ 37  36  34]
  [ 37  36  34]
  ...
  [ 37  36  34]
  [ 37  36  34]
  [ 38  37  35]]

 [[ 37  36  34]
  [ 37  36  34]
  [ 37  36  34]
  ...
  [ 41  40  38]
  [ 39  38  36]
  [ 42  41  39]]]
120000
(200, 200, 3)
[[[ 83  80  75]
  [ 82  79  74]
  [ 80  77  72]
  ...
  [129 124 120]
  [121 116 112]
  [124 119 115]]

 [[ 84  81  76]
  [ 79  76  71]
  [ 83  80  75]
  ...
  [121 116 112]
  [115 110 106]
  [123 118 114]]

 [[ 76  73  68]
  [ 70  67  62]
  [ 72  69  64]
  ...
  [125 120 116]
  [123 118 114]
  [130 125 121]]

 ...

 [[ 41  4

In [ ]:
pic = 2
for i in range(1,len(fileList)):
    print("PIC NO : ",pic)
    im = Image.open(dirName+"\\"+fileList[i])           
    im.show()
    original_array = np.array(im)
    print(original_array.shape)
    print(original_array.size)
    print(original_array)
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    print(resized_array.size)
    print(resized_array.shape)
    print(resized_array)
    main_list.append(resized_array)
    pic = pic+1

In [5]:
len(main_list)

1

In [6]:
main_list

[array([[[ 83,  80,  75],
         [ 82,  79,  74],
         [ 80,  77,  72],
         ...,
         [129, 124, 120],
         [121, 116, 112],
         [124, 119, 115]],
 
        [[ 84,  81,  76],
         [ 79,  76,  71],
         [ 83,  80,  75],
         ...,
         [121, 116, 112],
         [115, 110, 106],
         [123, 118, 114]],
 
        [[ 76,  73,  68],
         [ 70,  67,  62],
         [ 72,  69,  64],
         ...,
         [125, 120, 116],
         [123, 118, 114],
         [130, 125, 121]],
 
        ...,
 
        [[ 41,  40,  38],
         [ 46,  45,  43],
         [ 42,  41,  39],
         ...,
         [ 38,  37,  35],
         [ 39,  38,  36],
         [ 53,  52,  50]],
 
        [[ 39,  38,  36],
         [ 38,  37,  35],
         [ 38,  37,  35],
         ...,
         [ 39,  38,  36],
         [ 39,  38,  36],
         [ 42,  41,  39]],
 
        [[ 38,  37,  35],
         [ 32,  31,  29],
         [ 32,  32,  30],
         ...,
         [ 39,  38,  36],
  

In [10]:
def main():
    
    main_arr= np.array(main_list)
    print("FINAL NUMPY ARRAY :\n\n ",main_arr)
    return main_arr

In [14]:
main_arr.shape

AttributeError: 'function' object has no attribute 'shape'

In [12]:
main_arr.ndim


NameError: name 'main_arr' is not defined

In [13]:
main_arr.size

NameError: name 'main_arr' is not defined